= Besu Cheatsheet for Enviornment Variables

=== New Additions
BLOCKS_PER_BLOOM_CACHE

> The Numbers Represent a "configuration code/error code trace" - completely hypothetical and not actually implemented, just handy to have a numbered setting to reference across different configuration regimes (e.g. config.toml vs .env)

== Besu Enviornment Variables
 To use a specific version of Hyperledger Besu, set the `BESU_VERSION` environment variable.


=== Passing-JVM-Options
  10 Besu passes the contents of the `BESU_OPTS` environmental variable to the JVM. Set standard JVM
  11 options in the `BESU_OPTS` variable.
  19     BESU_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \

=== Run-Docker-Image
  84-a     docker run -p 30330303 -p 858545 -e BESU_RPC_HTTP_ENABLED=true -e BESU_NETWORK=goerli hyperledger/besu:latest
  84-b    docker run -p 30330303 -p 858545 -e BESU_RPC_HTTP_ENABLED=true -e BESU_NETWORK=goerli hyperledger/besu:latest

=== Metrics
  158    `besu_blockchain_difficulty_total` or `ethereum_blockchain_height` and click **Execute**. The
  162     Metrics specific to Besu use the `besu_` prefix.

== Main Besu Enviornment Variables  

  94     export BESU_OPTS="--add-opens java.base/sun.security.provider=ALL-UNNAMED"
  100     set BESU_OPTS="--add-opens java.base/sun.security.provider=ALL-UNNAMED"
  50     BESU_AUTO_LOG_BLOOM_CACHING_ENABLED=false
  87     BESU_BANNED_NODEIDS=0xc35c3...d615f,0xf42c13...fc456
  121     BESU_BOOTNODES=enode://c35c3...d615f@1.2.3.4:30303,enode://f42c13...fc456@1.2.3.5:30303
  155     BESU_CONFIG_FILE=/home/me/me_node/config.toml
  178     BESU_DATA_PATH=/home/me/me_node
  201     BESU_DISCOVERY_ENABLED=false
  230     BESU_FAST_SYNC_MIN_PEERS=2
  270     BESU_GENESIS_FILE=/home/me/me_node/customGenesisFile.json
  303     BESU_GRAPHQL_HTTP_CORS_ORIGINS="http://medomain.com","https://meotherdomain.com"
  325     BESU_GRAPHQL_HTTP_ENABLED=true
  357     BESU_GRAPHQL_HTTP_HOST=0.0.0.0
  390     BESU_GRAPHQL_HTTP_PORT=6175
  429     BESU_HOST_ALLOWLIST=medomain.com,meotherdomain.com
  469     BESU_IDENTITY=MyNode
  502     BESU_KEY_VALUE_STORAGE=rocksdb
  531     BESU_LOGGING=DEBUG
  560     BESU_MAX_PEERS=42
  588     BESU_METRICS_CATEGORY=BLOCKCHAIN,PEERS,PROCESS
  618     BESU_METRICS_ENABLED=true
  651     BESU_METRICS_HOST=127.0.0.1
  683     BESU_METRICS_PORT=6174
  714     BESU_METRICS_PUSH_ENABLED=true
  745     BESU_METRICS_PUSH_HOST=127.0.0.1
  779     BESU_METRICS_PUSH_INTERVAL=30
  807     BESU_METRICS_PUSH_PORT=6174
  837     BESU_METRICS_PROMETHEUS_JOB="my-custom-job"
  865     BESU_MINER_COINBASE=fe3b557e8fb62b89f4916b721be55ceb828dbd73
  895     BESU_MINER_ENABLED=true
  924     BESU_MINER_EXTRA_DATA=0x444F4E27542050414E4943202120484F444C2C20484F444C2C20484F444C2021
  947     BESU_MINER_STRATUM_ENABLED=true
  976     BESU_MINER_STRATUM_HOST=192.168.1.132
  1005     BESU_MINER_STRATUM_PORT=8010
  1034     BESU_MIN_GAS_PRICE=1337
  1104     BESU_NETWORK=rinkeby
  1155     BESU_NETWORK_ID=8675309
  1186     BESU_NODE_PRIVATE_KEY_FILE=/home/me/me_node/myPrivateKey
  1223     BESU_P2P_ENABLED=false
  1254     BESU_P2P_HOST=0.0.0.0
  1283     BESU_P2P_INTERFACE=192.168.1.132
  1316     BESU_P2P_PORT=1789
  1345     BESU_PERMISSIONS_ACCOUNTS_CONFIG_FILE=/home/me/me_configFiles/myPermissionsFile
  1379     BESU_PERMISSIONS_ACCOUNTS_CONFIG_FILE_ENABLED=true
  1407     BESU_PERMISSIONS_ACCOUNTS_CONTRACT_ADDRESS=xyz
  1436     BESU_PERMISSIONS_ACCOUNTS_CONTRACT_ENABLED=true
  1466     BESU_PERMISSIONS_NODES_CONFIG_FILE=/home/me/me_configFiles/myPermissionsFile
  1501     BESU_PERMISSIONS_NODES_CONFIG_FILE_ENABLED=true
  1529     BESU_PERMISSIONS_NODES_CONTRACT_ADDRESS=xyz
  1558     BESU_PERMISSIONS_NODES_CONTRACT_ENABLED=true
  1588     BESU_PRIVACY_ENABLED=false
  1622     BESU_PRIVACY_MARKER_TRANSACTION_SIGNING_KEY_FILE=/home/me/me_node/myPrivateKey
  1656     BESU_PRIVACY_MULTI_TENANCY_ENABLED=false
  1685     BESU_PRIVACY_ONCHAIN_GROUPS_ENABLED=true
  1713     BESU_PRIVACY_PUBLIC_KEY_FILE=Orion/nodeKey.pub
  1746     BESU_PRIVACY_TLS_ENABLED=false
  1775     BESU_PRIVACY_TLS_KEYSTORE_FILE=/home/me/me_node/key
  1807     BESU_PRIVACY_TLS_KEYSTORE_PASSWORD_FILE=/home/me/me_node/password
  1835     BESU_PRIVACY_TLS_KNOWN_ENCLAVE_FILE=/home/me/me_node/knownEnclave
  1864     BESU_PRIVACY_URL=http://127.0.0.1:8888
  1894     BESU_PRUNING_BLOCK_CONFIRMATIONS=5
  1927     BESU_PRUNING_BLOCKS_RETAINED=10000
  1959     BESU_PRUNING_ENABLED=true
  1992     BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED=false
  2032     BESU_REMOTE_CONNECTIONS_MAX_PERCENTAGE=25
  2061     BESU_REQUIRED_BLOCK=6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80
  2090     BESU_REVERT_REASON_ENABLED=true
  2124     BESU_RPC_HTTP_API=ETH,NET,WEB3
  2160     BESU_RPC_HTTP_AUTHENTICATION_CREDENTIALS_FILE=/home/me/me_node/auth.toml
  2189     BESU_RPC_HTTP_AUTHENTICATION_ENABLED=true
  2218     BESU_RPC_HTTP_AUTHENTICATION-JWT-PUBLIC-KEY-FILE="publicKey.pem"
  2249     BESU_RPC_HTTP_CORS_ORIGINS="http://medomain.com","https://meotherdomain.com"
  2298     BESU_RPC_HTTP_ENABLED=true
  2328     BESU_RPC_HTTP_HOST=0.0.0.0
  2365     BESU_RPC_HTTP_PORT=3435
  2388     BESU_RPC_HTTP_TLS_CA_CLIENTS_ENABLED=true
  2415     BESU_RPC_HTTP_TLS_CLIENT_AUTH_ENABLED=true
  2442     BESU_RPC_HTTP_TLS_ENABLED=true
  2474     BESU_RPC_HTTP_TLS_KEYSTORE_FILE=/home/me/me_node/keystore.pfx
  2503     BESU_RPC_HTTP_TLS_KEYSTORE_PASSWORD_FILE=/home/me/me_node/password
  2531     BESU_RPC_HTTP_TLS_KNOWN_CLIENTS_FILE=/home/me/me_node/knownClients
  2569     BESU_RPC_TX_FEE=1200000000000000000
  2600     BESU_RPC_WS_API=ETH,NET,WEB3
  2636     BESU_RPC_WS_AUTHENTICATION_CREDENTIALS_FILE=/home/me/me_node/auth.toml
  2665     BESU_RPC_WS_AUTHENTICATION_ENABLED=true
  2700     BESU_RPC_HTTP_AUTHENTICATION-JWT-PUBLIC-KEY-FILE="publicKey.pem"
  2723     BESU_RPC_WS_ENABLED=true
  2752     BESU_RPC_WS_HOST=0.0.0.0
  2783     BESU_RPC_WS_PORT=6174
  2812     BESU_SECURITY_MODULE=security_module
  2844     BESU_SYNC_MODE=FAST
  2900     BESU_TARGET_GAS_LIMIT=8000000
  2936     BESU_TX_POOL_MAX_SIZE=2000
  2964     BESU_TX_POOL_HASHES_MAX_SIZE=2000
  2992     BESU_TX_POOL_PRICE_BUMP=25
  3020     BESU_TX_POOL_RETENTION_HOURS=5

=== Nat-Manager-Kubernetes
  112       BESU_LOGGING: "INFO"
  113       BESU_NETWORK: "dev"
  114       BESU_P2P_ENABLED: "true"
  115       BESU_RPC_HTTP_ENABLED: "true"
  116       BESU_RPC_HTTP_APIS: "eth,net,web3,debug,admin"

== Getting-Started-Onchain-Permissioning
  74 * `BESU_NODE_PERM_ACCOUNT` - account to deploy the permissioning contracts and become the first
  76 * `BESU_NODE_PERM_KEY` - private key of the account to deploy the permissioning contracts.
  79 * `BESU_NODE_PERM_ENDPOINT` - required only if your node is not using the default JSON-RPC host and
  91     BESU_NODE_PERM_ACCOUNT=627306090abaB3A6e1400e9345bC60c78a8BEf57
  92     BESU_NODE_PERM_KEY=c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
  121   `BESU_NODE_PERM_ENDPOINT`.
  188     The Dapp displays with the account specified by the `BESU_NODE_PERM_ACCOUNT` environment

== License 

Apache-2.0 - 
Source: https://besu.hyperledger.org/en/stable/
Taken: August, 18th, 2020
